### PR TITLE
#118: Add feature: async backup/restore

### PR DESCRIPTION
**Pull request by sampraxis**
Improve backup/restore process by using adhoc task.
Added new setting for switch in between "immediate" and "asynchronous" mode.
Fix session lock error.

### CODE REVIEW

**Review by frederikmillingpytlick — CHANGES_REQUESTED** [review]
Fix tests

**Review by frederikmillingpytlick — APPROVED** [review]
:rocket:

**Comment by sampraxis** [comment]
#119 PR https://github.com/praxisdigital/moodle-block_sharing_cart/pull/121 is reviewed and approved by @AraPraxis

**Review by frederikmillingpytlick — APPROVED** [review]
:rocket:

**Pull request merged**
